export const footer: string
export const mainSectionFooter: string
export const secondarySectionFooter: string
export const footerSections: string
export const rightsReserved: string
export const socialMediaContainer: string
export const iconsContainer: string
export const logo: string
export const mainSectionFooter__column: string
export const showDesktop: string
export const showMobile: string
