export const sixthSection: string
export const sixthSection__leftSide: string
export const sixthSection__rightSide: string
export const sixthSection__leftSide__bullets: string
export const sixthSection__leftSide__description: string
export const sixthSection__rightSide__bullets__container: string
export const sixthSection__rightSide__credentials: string
export const buttons: string
export const buttons__container: string
export const buttons__left: string
export const buttons__right: string
export const buttons__inactive: string
export const buttons__active: string
export const sixthSection__container: string
