apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web 
  name: web
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gatacaid/website:4.0.7-pre
          ports:
          - containerPort: 80 
            name: web
            protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: web
  labels:
    app: web
spec:
  type: NodePort
  ports:
    - port: 80
      name: web
      protocol: TCP
      targetPort: 80
  selector:
    app: web

