---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: strapiweb
  name: strapiweb
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapiweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: strapiweb
    spec:
      containers:
        - name: strapiweb
          image: ghcr.io/gataca-io/gataca.io/strapi:6.1.0
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  key: APP_KEYS
                  name: strapi-api
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  key: API_TOKEN_SALT
                  name: strapi-api
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: ADMIN_JWT_SECRET
                  name: strapi-api
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: strapi-api
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_HOST
              value: "postgres.database.svc.cluster.local"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: strapidb-secret
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: strapidb-secret
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: strapidb-secret
            - name: AWS_BUCKET
              value: media-gataca
            - name: AWS_BUCKET_NAME
              value: media-gataca
            - name: AWS_REGION
              value: eu-west-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: strapi-api
            - name: AWS_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_SECRET
                  name: strapi-api
          ports:
            - containerPort: 1337
              name: strapiweb
              protocol: TCP
          volumeMounts:
      imagePullSecrets:
        - name: ghcr
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: strapiadmin
  name: strapiadmin
  namespace: web
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 1337
      name: strapiadminport
      targetPort: 1337
  selector:
    app: strapiweb
