export const credential__container: string
export const iconSmall: string
export const iconMedium: string
export const iconLarge: string
export const iconXLarge: string
export const logoSmall: string
export const logoLarge: string
export const white: string
export const purpleGradient: string
export const tealGradient: string
export const pinkGradient: string
export const teal: string
export const blue: string
export const pink: string
export const yellow: string
export const grey: string
export const darkBlue: string
export const green: string
export const orange: string
export const header__container: string
export const actionItems__container: string
export const content__container: string
export const icon: string
export const logo: string
