export const buttonStrapi: string
export const disabled: string
export const outlineButton: string
export const text: string
export const buttonSM: string
export const whiteColor: string
export const blackColor: string
export const greyColor: string
export const noPadding: string
export const fullWidthButton: string
