export const subHeadingsLayout__container: string
export const headingCards: string
export const blockAlignLeft: string
export const blockAlignCenter: string
export const blockAlignRight: string
export const slotAlignLeft: string
export const slotAlignRight: string
export const subHeading__container: string
export const image__container: string
