export const itemsContainer: string
export const description: string
export const linkMore: string
export const threeCol: string
export const noShadow: string
export const iconContainer: string
export const secondCategory: string
export const opened: string
export const descriptionContainer: string
export const iconSectors: string
