export const mediaStepsSlider__container: string
export const mediaStepsSlider__leftSide: string
export const mediaStepsSlider__rightSide: string
export const imageContainer: string
export const mediaStepsSlider__buttons__mobile: string
export const mediaStepsSlider__buttons__desktop: string
export const mediaStepsSlider__rightSide__data: string
export const mediaStepsSlider__rightSide__data__item: string
export const heading__mobile: string
export const heading__desktop: string
export const heading: string
