export const buttonIcon: string
export const disabled: string
export const squareButton: string
export const greenFill: string
export const yellowFill: string
export const blueFill: string
export const lightPurpleFill: string
export const tealFill: string
export const pinkFill: string
export const redFill: string
export const buttonSM: string
