export const buttonIcon: string
export const disabled: string
export const squareButton: string
export const greenColor: string
export const yellowColor: string
export const blueColor: string
export const lightPurpleColor: string
export const tealColor: string
export const pinkColor: string
export const redColor: string
export const buttonSM: string
