export const mobileMenu: string
export const mobileMenu__Content: string
export const mobileMenu__header: string
export const opened: string
export const buttonsContainer: string
export const logo: string
export const visibleLogo: string
export const hiddenLogo: string
export const backLink: string
export const visibleBackLink: string
export const hiddenBackLink: string
export const backLink__text: string
export const closeMenuIcon: string
export const menuContentVisible: string
export const menuIconContainer: string
