export const tableContainer: string
export const table__header: string
export const table__header__container: string
export const table__header__cell: string
export const table__header__cell__content: string
export const licenseSave: string
export const table__body: string
export const table__body__row: string
export const table__body__row__category: string
export const table__body__row__subcategory: string
export const markdown: string
