export const tableContainer: string
export const table__header: string
export const periodToggle: string
export const periodCheckbox: string
export const periodCheckboxLabel: string
export const table__header__container: string
export const table__header__cell: string
export const table__header__cell__content: string
export const license__header: string
export const licenseName: string
export const license__header__popularTag: string
export const licensePrice: string
export const licensePriceLarge: string
export const licenseSave: string
export const licenseCustomPrice: string
export const licenseAdapted: string
export const license__button: string
export const table__body: string
export const table__body__row: string
export const table__body__row__category: string
export const table__body__row__subcategory: string
export const table__body__row__cell__icon: string
