export const checksGreyPanelTwoColumns: string
export const checksGreyPanelTwoColumns__leftSide: string
export const checksGreyPanelTwoColumns__rightSide: string
export const checksGreyPanelTwoColumns__rightSide__bullets: string
export const checksGreyPanelTwoColumns__rightSide__bullets__container: string
export const checksGreyPanelTwoColumns__container: string
export const checksGreyPanelTwoColumns__container: string
export const bullet__description: string
