export const highlightSubHeadingCard__container: string
export const highlightSubHeadingCard__mainContent: string
export const highlightSubHeadingCard__subHeading: string
export const highlightSubHeadingCard__fullWidthCard: string
