export const dynamicCardComponent__container: string
export const dynamicCardComponent: string
export const dynamicCardComponent__elements: string
export const dynamicCard__container: string
export const dynamicCard: string
export const alignCenter: string
export const alignBottom: string
export const background: string
export const headingContainer: string
