export const secondSection__container: string
export const secondSection: string
export const secondSection__leftSide: string
export const buttons_container: string
export const form__label: string
export const form__input: string
export const form__button: string
export const secondSection__rightSide: string
export const secondSection__imageContainer: string
