export const formLayout: string
export const formLayout__container: string
export const formLayout__options: string
export const formLayout__leftSide: string
export const formLayout__rightSide: string
export const image__container: string
export const selectorImage__desktop: string
export const selectorImage__mobile: string
export const background: string
export const headingContainer: string
export const greyBackground: string
export const blackBackground: string
export const form__container: string
export const formLayout__header: string
