export const formLayout: string
export const formLayout__container: string
export const formLayout__options: string
export const formLayout__leftSide: string
export const formLayout__rightSide: string
export const image__container: string
export const background: string
export const headingSlotContainer: string
export const greyBackground: string
export const blackBackground: string
export const form__container: string
export const formLayout__header: string
export const actionCards__container: string
