export const contentTable: string
export const showDesktop: string
export const showMobile: string
export const contentTableContainer: string
export const slotsContainer: string
export const tableContainer: string
export const rightColumnContainer: string
export const rightColumnContainer__changeOrder: string
export const rightColumnContainer: string
export const contentTable__subHeadingContainer: string
