export const thirdSection: string
export const thirdSection__leftSide: string
export const thirdSection__rightSide: string
export const thirdSection__rightSide__data: string
export const thirdSection__rightSide__data__item: string
export const thirdSection__rightSide__data__item__title: string
export const thirdSection__rightSide__data__item__desc: string
export const buttons__container: string
export const buttons__left: string
export const buttons__inactive: string
export const buttons__active: string
