export const secondSection__container: string
export const secondSection: string
export const secondSection__blogsContainer: string
export const secondSection__rightSide: string
export const secondSection__rightSide__bullets: string
export const categorySelectedOption: string
export const categoryOption: string
export const categoriesContainer: string
export const loadMoreButton: string
