export const sideCardsSlider__container: string
export const sideCardsSlider: string
export const sideCardsSlider__heading: string
export const sideCardsSlider__slotsButton: string
export const sideCardsSlider__slotsButtonContainer: string
export const slots__elements: string
export const sideCardsSlider__buttons: string
export const textAlignRight: string
export const background: string
export const oneTestimonialCard: string
