export const dynamicSelector: string
export const dynamicSelector__container: string
export const dynamicSelector__options: string
export const dynamicSelector__leftSide: string
export const dynamicSelector__rightSide: string
export const image__container: string
export const selectorImage__desktop: string
export const selectorImage__mobile: string
export const background: string
export const headingContainer: string
export const heading_selector_container: string
export const fiftyFifty: string
export const twentyFiveSeventyFive: string
export const maxWidth: string
export const media__container: string
export const selectorAlignTop: string
export const selectorAlignCenter: string
