export const license__features__list__item: string
export const notAvailableNow: string
export const featureNotAvailableNow: string
export const featureName: string
export const license__features__list__item__content: string
export const featureQuantity: string
export const license: string
export const currentLicense: string
export const license__header: string
export const license__header__title: string
export const license__header__popularTag: string
export const license__description: string
export const license__price: string
export const license__priceLarge: string
export const license__save: string
export const license__customPrice: string
export const license__customPriceLarge: string
export const license__adapted: string
export const license__adaptedLarge: string
export const license__features: string
export const license__features__title: string
export const license__features__list: string
export const license__button: string
