---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Web Content
- type: document
  path: content/data/homeData.json
  label: "- Home -"
- type: document
  path: content/data/partnersSectionData.json
  label: "- Partners -"
- type: document
  path: content/data/aboutData.json
  label: "- About -"
- type: document
  path: content/data/faqData.json
  label: "- Faq -"
- type: document
  path: content/data/footerSectionData.json
  label: "- Footer -"
- type: document
  path: content/data/insightsData.json
  label: "- Insights Page -"
- type: document
  path: content/data/pressSectionData.json
  label: "- Press Releases -"
- type: heading
  label: Products
- type: document
  path: content/data/productsData.json
  label: "- Products Page -"
- type: document
  path: content/data/identify.json
  label: "- Wallet -"
- type: document
  path: content/data/credentials.json
  label: "- Certify -"
- type: document
  path: content/data/connect.json
  label: " - Connect -"
- type: heading
  label: Content
- type: document
  path: content/data/configMetaData.json
  label: Site Info
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: content/mdpages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/drafts
  label: Blog Drafts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
upload_dir: static/images
public_path: "/static/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
