export const chipStrapi: string
export const disabled: string
export const outlineChip: string
export const buttonMD: string
export const buttonSM: string
export const greenColor: string
export const yellowColor: string
export const blueColor: string
export const lightPurpleColor: string
export const tealColor: string
export const pinkColor: string
export const redColor: string
export const buttonSM: string
export const purpleColor: string
export const greyColor: string
export const blackColor: string
export const roundChip: string
export const roundChip: string
export const text: string
