export const tableContainer: string
export const header__container: string
export const license__button: string
export const card: string
export const selector: string
export const card__header: string
export const popularTag: string
export const card__row: string
export const icon: string
export const markdown: string
