export const fourthSection: string
export const fourthSection__content: string
export const header: string
export const listContainer: string
export const listTeam: string
export const listTeam__content: string
export const leftColumn: string
export const name: string
export const title: string
export const rightColumn: string
