export const carrouselLogos: string
export const clientsLogo: string
export const clientsLogo__container: string
export const clientsLogo__carrousel: string
export const clientsLogo__loop: string
export const clientsLogo__static: string
export const clientsLogo__carrouselItem: string
export const lightBackground: string
export const darkBackground: string
