export const checksGreyPanel__leftSide: string
export const checksGreyPanel__rightSide: string
export const checksGreyPanel__rightSide__bullets: string
export const checksGreyPanel__rightSide__bullets__container: string
export const checksGreyPanel__container: string
export const bullet__description: string
export const bullets__container__description: string
