---
label: Products Page
hide_body: false
fields:
- name: metas
  type: field_group
  config: {}
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: description
    type: text
    config:
      required: false
    label: Description
  label: Metas
- type: field_group
  name: introProductsSection
  label: Intro Section
  fields:
  - name: title
    type: text
    default: PRODUCTS
    config:
      required: false
      wysiwyg: false
    label: Title
  - name: description
    type: textarea
    label: Description
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
- type: field_group_list
  name: productsData
  label: Products Section
  fields:
  - name: title
    type: text
    label: Product Name
    default: ''
    config:
      required: false
      wysiwyg: false
  - name: icon
    type: file
    label: Product Icon
    default: ''
    config:
      required: false
      wysiwyg: false
  - name: description
    type: textarea
    label: Product Description
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
  - name: bullets
    type: field_group_list
    default: ''
    label: Product Detail Bullets
    config:
    fields:
    - type: text
      name: title
      label: Bullet Title
      config:
        required: false
    - type: textarea
      name: description
      label: Bullet Description
      config:
        required: false
        wysiwyg: true
        schema:
          format: html-blocks
    - type: file
      name: image
      label: Bullet Icon
      config:
        required: false
  - name: mainImage
    type: file
    label: Main Product Image
    default: ''
    config:
      required: false
      wysiwyg: false
