---
label: products Page
hide_body: false
fields:
- name: metas
  type: field_group
  config: {}
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: description
    type: text
    config:
      required: false
    label: Description
  - name: facebookImage
    type: file
    config:
      required: false
    label: LinkedIn Image
  - name: linkedInImage
    type: file
    config:
      required: false
    label: Facebook Image
  - name: twitterImage
    type: file
    config:
      required: false
    label: Twitter Image
  label: Metas
- type: field_group
  name: introProductsSection
  label: Intro Section
  fields:
  - name: title
    type: text
    default: PRODUCTS
    config:
      required: false
      wysiwyg: false
    label: Title
  - name: description
    type: textarea
    label: Description
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
