export const fullWidthCard__container: string
export const fullWidthCard: string
export const fullWidthCard__heading: string
export const fullWidthCard__image: string
export const fullWidthCard__imageContainer: string
export const whiteBackground: string
export const greyBackground: string
export const lightPurpleBackground: string
export const fiftyFifty: string
export const twentyFiveSeventyFive: string
export const padding: string
