export const buttonStrapi: string
export const disabled: string
export const outlinedButton: string
export const onlyText: string
export const buttonLG: string
export const buttonSM: string
export const whiteFill: string
export const blackFill: string
export const greyFill: string
export const noPadding: string
