export const firstSection: string
export const firstSection__leftSide: string
export const firstSection__rightSide: string
export const firstSection__image__desktop: string
export const firstSection__image__mobile: string
export const firstSection__image__desktop__shadow: string
export const firstSection__image__desktop_container: string
export const firstSection__image__desktop__shadow_cont: string
