export const introBlogSkeleton__container: string
export const introBlogSkeleton: string
export const introBlogSkeleton__leftSide: string
export const introBlogSkeleton__leftSide__header: string
export const introBlogSkeleton__rightSide: string
export const introBlogSkeleton__imageContainer: string
export const skeleton: string
export const date: string
export const title: string
export const topic: string
export const timeReading: string
